twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        Application: '@App\Service\Application'
        Ressource: '@App\Service\Ressource'

when@test:
    twig:
        strict_variables: true
