twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        Application: '@App\Entity\Application'
        Ressources: '@App\Service\Ressource'
        Parametres: '@App\Service\Parametre'

when@test:
    twig:
        strict_variables: true
